ref:
  # path/to/reference/gDNA.fasta
    sequence:       /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fa
    fai:            /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fa.fai
    dict:           /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.dict
  # path/to/bwa/index/directory
    index:          /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/indexes/bwa/c.elegans-WBcel235
  # path/to/gtf/file/with/transcripts.gtf
    annotation:     /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/annotation/c.elegans-WBcel235.gtf
    mito_chr: MtDNA
    known_snps: "" # if empty, workflow will run do a 'bootstrap' run to generate high quality variants
    known_indels: "" # if empty, workflow will run do a 'bootstrap' run to generate high quality variants
    snpEff_dataDir: "./data/"
    snpEff_genome_ID: "WBcel235.86"

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"

modules:
  bamtools: bbc2/bamtools/bamtools-2.5.2
  bcftools: bbc2/bcftools/bcftools-1.17
  bedops: bbc2/bedops/bedops-2.4.41
  bedtools: bbc2/bedtools/bedtools-2.30.0
  bwa: bbc2/bwa/bwa-0.7.17
  fastqc: bbc2/fastqc/fastqc-0.12.1
  fastq_screen: bbc2/fastq_screen/fastq_screen-0.14.0
  gatk: bbc2/gatk/gatk-4.1.8.1
  multiqc: bbc2/multiqc/multiqc-1.14
  picard: bbc2/picard/picard-2.27.5
  qualimap: bbc2/qualimap/qualimap_v.2.2.2
  R: bbc2/R/alt/R-4.2.1-setR_LIBS_USER
  samblaster: bbc2/samblaster/samblaster-0.1.26
  samtools: bbc2/samtools/samtools-1.17
  snpEff: bbc2/SnpEff/SnpEff-5.1
  trim_galore: bbc2/trim_galore/trim_galore-0.6.0
  vt: bbc2/vt/vt-0.1.16
