ref:
  # path/to/reference/gDNA.fasta
    sequence:       /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fa
    fai:            /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fa.fai
    dict:           /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.dict
  # path/to/bwa/index/directory
    index:          /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/indexes/bwa/c.elegans-WBcel235
  # path/to/gtf/file/with/transcripts.gtf
    annotation:     /varidata/research/projects/bbc/versioned_references/2022-10-06_14.25.40_v10/data/c.elegans-WBcel235/annotation/c.elegans-WBcel235.gtf
    mito_chr: MtDNA
    known_snps: "" # if empty, workflow will run do a 'bootstrap' run to generate high quality variants
    known_indels: "" # if empty, workflow will run do a 'bootstrap' run to generate high quality variants
    snpEff_dataDir: "./data/"
    snpEff_genome_ID: "WBcel235.86"

shared_snakemake_repo: "/secondary/projects/bbc/research/shared_snakemake/"

modules:
  bamtools: bbc/bamtools/bamtools-2.5.1
  bcftools: bbc/bcftools/bcftools-1.12 
  bedops: bbc/bedops/bedops-2.4.37
  bedtools: bbc/bedtools/bedtools-2.29.2
  bwa: bbc/bwa/bwa-0.7.17
  fastqc: bbc/fastqc/fastqc-0.11.9
  fastq_screen: bbc/fastq_screen/fastq_screen-0.14.0
  gatk: bbc/gatk/gatk-4.1.8.1
  multiqc: bbc/multiqc/multiqc-1.9
  picard: bbc/picard/picard-2.23.3
  qualimap: bbc/qualimap/qualimap_v.2.2.2
  R: bbc/R/R-4.1.0-setR_LIBS_USER
  samblaster: bbc/samblaster/samblaster-0.1.24
  samtools: bbc/samtools/samtools-1.9
  snpEff: bbc/SnpEff/SnpEff-4.3t
  trim_galore: bbc/trim_galore/trim_galore-0.6.0
  vt: bbc/vt/vt-0.1.16
